version: '3'
services:

  db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - config/envs/.env

  app:
    container_name: app-container
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    #    command: uwsgi --ini uwsgi.ini
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

    #  nginx:
    #    container_name: nginx-container
    #    build: ./nginx
    #    restart: always
    #    ports:
    #      - "80:80"
    #    volumes:
    #      - app_data:/docker_app
    #      - ./log:/var/log/nginx
    #    depends_on:
    #      - app

    #   auto migrate django
#  migration:
#    build: ./app
#    command:
#      - /bin/sh
#      - -c
#      - |
#        python manage.py collectstatic --noinput
#        python manage.py migrate
#        python manage.py makemigrations musics
#        python manage.py migrate
#    volumes:
#      - app_data:/docker_app
#    depends_on:
#      - db

volumes:
  app:
  pgdata:
