version: '3'
services:

  web:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn django_docker.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    ports:
      - 8000
    env_file:
      - config/envs/.env.prod
    entrypoint:
      - sh
      - entrypoint.prod.sh

  nginx:
    container_name: nginx
    build: ./config/nginx
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  pgdata:
  static:
  media: